spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    username: 'pr_compilation'
    password: 'compilation'
    url: 'jdbc:postgresql://localhost/pr_compilation'
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    database: postgresql

jwt:
  issuer: 'nazarov.nh@gmail.com'
  signingKey: 'talspoc120nxjsapqke1d99'
  aAccessTokenDuration: 59
  aRefreshTokenDuration: 420

reflectoring:
  trace: true