CREATE TABLE IF NOT EXISTS users (
    user_id VARCHAR(36) PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    password VARCHAR(256) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS update_users__update_at ON users;
CREATE TRIGGER update_users__update_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE PROCEDURE update_time();
